version: '3'

services:
  thedb:
    image: postgres
    environment:
      - POSTGRES_DB=atol_dev
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - TZ='America/Sao_Paulo'
    ports:
      - 5432:5432